"""Bridge layer — the ONLY module in the codebase allowed to import MetaTrader5."""
from .mt5_backend import (
    connect, is_connected, mt5_call, ensure_symbol, reconnect_once,
    ORDER_FILLING_FOK, ORDER_FILLING_IOC, ORDER_FILLING_RETURN,
    ORDER_TYPE_BUY, ORDER_TYPE_SELL,
    ORDER_TYPE_BUY_LIMIT, ORDER_TYPE_SELL_LIMIT,
    ORDER_TYPE_BUY_STOP, ORDER_TYPE_SELL_STOP,
    TRADE_ACTION_DEAL, TRADE_ACTION_PENDING, TRADE_ACTION_MODIFY, TRADE_ACTION_REMOVE, TRADE_ACTION_SLTP,
    POSITION_TYPE_BUY, POSITION_TYPE_SELL,
    TIMEFRAME_M1, TIMEFRAME_M5, TIMEFRAME_M15, TIMEFRAME_M30,
    TIMEFRAME_H1, TIMEFRAME_H4, TIMEFRAME_D1, TIMEFRAME_W1, TIMEFRAME_MN1,
    COPY_TICKS_ALL, ACCOUNT_TRADE_MODE_DEMO, ORDER_TIME_GTC,
)

__all__ = [
    "connect", "is_connected", "mt5_call", "ensure_symbol", "reconnect_once",
    "ORDER_FILLING_FOK", "ORDER_FILLING_IOC", "ORDER_FILLING_RETURN",
    "ORDER_TYPE_BUY", "ORDER_TYPE_SELL",
    "ORDER_TYPE_BUY_LIMIT", "ORDER_TYPE_SELL_LIMIT",
    "ORDER_TYPE_BUY_STOP", "ORDER_TYPE_SELL_STOP",
    "TRADE_ACTION_DEAL", "TRADE_ACTION_PENDING", "TRADE_ACTION_MODIFY", "TRADE_ACTION_REMOVE", "TRADE_ACTION_SLTP",
    "POSITION_TYPE_BUY", "POSITION_TYPE_SELL",
    "TIMEFRAME_M1", "TIMEFRAME_M5", "TIMEFRAME_M15", "TIMEFRAME_M30",
    "TIMEFRAME_H1", "TIMEFRAME_H4", "TIMEFRAME_D1", "TIMEFRAME_W1", "TIMEFRAME_MN1",
    "COPY_TICKS_ALL", "ACCOUNT_TRADE_MODE_DEMO", "ORDER_TIME_GTC",
]
